//@version=6
indicator(title="Relative Strength Index", shorttitle="RSI", format=format.price, precision=2, timeframe="", timeframe_gaps=true)
ma(source, length, type) =>
    switch type
        "SMA" => ta.sma(source, length)
        "Bollinger Bands" => ta.sma(source, length)
        "EMA" => ta.ema(source, length)
        "SMMA (RMA)" => ta.rma(source, length)
        "WMA" => ta.wma(source, length)
        "VWMA" => ta.vwma(source, length)

rsiLengthInput = input.int(13, minval=1, title="RSI Length", group="RSI Settings")
rsiSourceInput = input.source(close, "Source", group="RSI Settings")
maTypeInput = input.string("EMA", title="MA Type", options=["SMA", "Bollinger Bands", "EMA", "SMMA (RMA)", "WMA", "VWMA"], group="MA Settings", display = display.data_window)
maLengthInput = input.int(13, title="MA Length", group="MA Settings", display = display.data_window)
WMATypeInput = input.string("WMA", title="WMA Type", options=["SMA", "Bollinger Bands", "EMA", "SMMA (RMA)", "WMA", "VWMA"], group="MA Settings", display = display.data_window)
WMALengthInput = input.int(55, title="WMA Length", group="MA Settings", display = display.data_window)
//bbMultInput = input.float(2.0, minval=0.001, maxval=50, title="BB StdDev", group="MA Settings", display = display.data_window)
//calculateDivergence = input.bool(false, title="Calculate Divergence", group="RSI Settings", display = display.data_window, tooltip = "Calculating divergences is needed in order for divergence alerts to fire.")

change = ta.change(rsiSourceInput)
up = ta.rma(math.max(change, 0), rsiLengthInput)
down = ta.rma(-math.min(change, 0), rsiLengthInput)
rsi = down == 0 ? 100 : up == 0 ? 0 : 100 - (100 / (1 + up / down))
rsiMA = ma(rsi, maLengthInput, maTypeInput)
rsiWMA = ma(rsi, WMALengthInput, WMATypeInput)
var isBB = maTypeInput == "Bollinger Bands"

rsiPlot = plot(rsi, "RSI", color=#00fc00, linewidth=2,style=plot.style_stepline)
plot(rsiMA, "RSI-based MA", color=#fa1717, linewidth=2)
plot(rsiWMA, "RSI-based WMA", color=#0018f0, linewidth=2)
rsiUpperBand = hline(80, "RSI Upper Band", color=#00e41e)
rsiWarnUpperBand = hline(70, "RSI Warning Upper Band", color=#fde507)
rsiSidewayHighBand = hline(60, "RSI Sideway Higher Band", color=#0bf0f8)
midline = hline(50, "RSI Middle Band", color=color.new(#787B86, 50))
rsiSidewayLowBand = hline(40, "RSI Sideway Lower Band", color=#0bf0f8)
rsiWarnLowerBand = hline(30, "RSI Warning Lower Band", color=#fde507)
rsiLowerBand = hline(20, "RSI Lower Band", color=#f70101)
